name: send dispatch

on:
  push:
    branches:
      - sync-repo

jobs:
  dispatch:
      runs-on: ubuntu-latest
      steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ChloePlanet/sync-sysl
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: sync
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
