name: Sync Repo

on:
  schedule:
    - cron:  "0/5 * * * 1"
  # - cron:  "0 14 * * 1"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://${{ secrets.SYNC_ACCESS_TOKEN }}@${{ secrets.SYNC_SRC_REPO }}.git"
        source_branch: "master"
        destination_repo: "https://${{ secrets.SYNC_ACCESS_TOKEN }}@github.com/ChloePlanet/sync-sysl.git"
        destination_branch: "master"

    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://${{ secrets.SYNC_ACCESS_TOKEN }}@${{ secrets.SYNC_SRC_REPO }}.git"
        source_branch: "refs/tags/*"
        destination_repo: "https://${{ secrets.SYNC_ACCESS_TOKEN }}@github.com/ChloePlanet/sync-sysl.git"
        destination_branch: "refs/tags/*"

# on: [pull_request]
#   # schedule:
#   # - cron:  "0 14 * * 1"

# jobs:
#   repo-sync:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: sync master branch
#       uses: anz-bank/github-sync@master
#       with:
#         workflow_filename: "sync-repo.yml"
#         source_repo: https://${{ secrets.SYNC_ACCESS_TOKEN }}@${{ secrets.SYNC_SRC_REPO }}.git
#         source_branch: "master"
#         destination_branch: "master"
#         github_token: ${{ secrets.SYNC_ACCESS_TOKEN }}
#         github_email: "sysl.usr@gmail.com"
#         github_name: "SyslBot"
#         tags: true
